import { describe, expect, it } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { runProtect, runVerify } from '../../src/protect/install/index.js';

const read = (dir: string, rel: string) => readFileSync(path.join(dir, rel), 'utf8');
const count = (hay: string, needle: string) => hay.split(needle).length - 1;
const tmp = (p: string) => mkdtempSync(path.join(tmpdir(), p));

describe('Express adapter', () => {
  function expressApp(): string {
    const dir = tmp('ps-express-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', dependencies: { express: '^4.19.0' } }));
    mkdirSync(path.join(dir, 'src'), { recursive: true });
    writeFileSync(
      path.join(dir, 'src/server.ts'),
      "import express from 'express';\nconst app = express();\napp.use(express.json());\napp.listen(3000);\n",
    );
    return dir;
  }

  it('scaffolds the guard and wires app.use(patchstackMiddleware) after body parsing', () => {
    const dir = expressApp();
    try {
      const res: any = runProtect(dir);
      expect(res.status).toBe('wired');
      expect(res.adapter).toBe('express');
      expect(existsSync(path.join(dir, 'src/patchstack/guard.ts'))).toBe(true);
      const server = read(dir, 'src/server.ts');
      expect(server).toContain('import { patchstackMiddleware } from "./patchstack/guard";');
      expect(server).toContain('app.use(patchstackMiddleware);');
      expect(server.indexOf('app.use(express.json())')).toBeLessThan(server.indexOf('app.use(patchstackMiddleware)'));
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('is idempotent (re-run does not duplicate the middleware)', () => {
    const dir = expressApp();
    try {
      runProtect(dir);
      runProtect(dir);
      expect(count(read(dir, 'src/server.ts'), 'app.use(patchstackMiddleware)')).toBe(1);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('wires the plain ESM server.js shape generated by Bolt', () => {
    const dir = tmp('ps-express-esm-');
    writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({ name: 'minimal-todo-app', type: 'module', main: 'server.js', dependencies: { express: '^4.21.2' } }),
    );
    writeFileSync(
      path.join(dir, 'server.js'),
      "import express from 'express';\nconst app = express();\napp.use(express.json());\napp.post('/api/tasks', (req, res) => res.status(201).json(req.body));\napp.listen(3000);\n",
    );
    const uuid = '3f1a9c2e-1b4d-4c8a-9e2f-7a6b5c4d3e2f';
    writeFileSync(path.join(dir, '.patchstackrc.json'), JSON.stringify({ siteUuid: uuid }));
    try {
      runProtect(dir);
      const server = read(dir, 'server.js');
      expect(server).toContain('import { patchstackMiddleware } from "./patchstack/guard.js";');
      expect(server.indexOf('app.use(express.json())')).toBeLessThan(server.indexOf('app.use(patchstackMiddleware)'));
      expect(server.indexOf('app.use(patchstackMiddleware)')).toBeLessThan(server.indexOf("app.post('/api/tasks'"));
      expect(existsSync(path.join(dir, 'patchstack/guard.js'))).toBe(true);
      expect(existsSync(path.join(dir, 'patchstack/guard.ts'))).toBe(false);
      expect(read(dir, 'patchstack/guard.js')).toContain('active.express()');
      expect(read(dir, 'patchstack/guard.js')).toContain(uuid);
      expect(runVerify(dir).wired).toBe(true);
      execFileSync(process.execPath, ['--check', path.join(dir, 'server.js')]);
      execFileSync(process.execPath, ['--check', path.join(dir, 'patchstack/guard.js')]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('wires CommonJS server.js without adding ESM syntax', () => {
    const dir = tmp('ps-express-cjs-');
    writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({ name: 'express-cjs', main: 'server.js', dependencies: { express: '^4.21.2' } }),
    );
    writeFileSync(
      path.join(dir, 'server.js'),
      "const express = require('express');\nconst app = express();\napp.use(express.json());\napp.post('/api/tasks', (req, res) => res.status(201).json(req.body));\n",
    );
    try {
      runProtect(dir);
      const server = read(dir, 'server.js');
      expect(server).toContain('const { patchstackMiddleware } = require("./patchstack/guard.cjs");');
      expect(existsSync(path.join(dir, 'patchstack/guard.cjs'))).toBe(true);
      expect(read(dir, 'patchstack/guard.cjs')).toContain('active.express()');
      expect(runVerify(dir).wired).toBe(true);
      execFileSync(process.execPath, ['--check', path.join(dir, 'server.js')]);
      execFileSync(process.execPath, ['--check', path.join(dir, 'patchstack/guard.cjs')]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  const parserVariants: Array<{ label: string; imports: string; parser: string }> = [
    { label: 'express.urlencoded()', imports: "import express from 'express';", parser: 'app.use(express.urlencoded({ extended: true }));' },
    { label: 'body-parser', imports: "import express from 'express';\nimport bodyParser from 'body-parser';", parser: 'app.use(bodyParser.json());' },
    { label: 'a destructured json()', imports: "import express, { json } from 'express';", parser: 'app.use(json());' },
  ];
  for (const { label, imports, parser } of parserVariants) {
    it(`wires after ${label} (not just express.json)`, () => {
      const dir = tmp('ps-express-parser-');
      writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ type: 'module', dependencies: { express: '^4.21.2' } }));
      writeFileSync(
        path.join(dir, 'server.js'),
        `${imports}\nconst app = express();\n${parser}\napp.get('/', (req, res) => res.end());\n`,
      );
      try {
        runProtect(dir);
        const server = read(dir, 'server.js');
        expect(server).toContain('app.use(patchstackMiddleware);');
        expect(server.indexOf('app.use(patchstackMiddleware)')).toBeLessThan(server.indexOf("app.get('/'"));
        expect(runVerify(dir).wired).toBe(true); // verify requires the guard to sit after the parser
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });
  }

  it('wires a self-buffering guard after app creation when there is no body parser', () => {
    const dir = tmp('ps-express-no-parser-');
    writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({ type: 'module', dependencies: { express: '^4.21.2' } }),
    );
    writeFileSync(
      path.join(dir, 'server.js'),
      "import express from 'express';\nconst app = express();\napp.post('/api/tasks', handler);\n",
    );
    try {
      runProtect(dir);
      const server = read(dir, 'server.js');
      // Wired: import + registration, mounted after app creation and before the route.
      expect(server).toContain('import { patchstackMiddleware } from "./patchstack/guard.js";');
      expect(server).toContain('app.use(patchstackMiddleware);');
      expect(server.indexOf('const app = express()')).toBeLessThan(server.indexOf('app.use(patchstackMiddleware)'));
      expect(server.indexOf('app.use(patchstackMiddleware)')).toBeLessThan(server.indexOf("app.post('/api/tasks'"));
      // The no-parser fallback uses the self-buffering node() guard, not express().
      expect(read(dir, 'patchstack/guard.js')).toContain('active.node()');
      expect(existsSync(path.join(dir, 'patchstack/guard.js'))).toBe(true);
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('Next.js adapter', () => {
  it('scaffolds middleware.ts + co-located rules when none exists', () => {
    const dir = tmp('ps-next-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', dependencies: { next: '^14.0.0' } }));
    try {
      const res: any = runProtect(dir);
      expect(res.status).toBe('wired');
      expect(res.adapter).toBe('nextjs');
      const mw = read(dir, 'middleware.ts');
      expect(mw).toContain('patchstack-next');
      expect(mw).toContain('config = { matcher:');
      expect(existsSync(path.join(dir, 'patchstack.rules.json'))).toBe(true);
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('does NOT overwrite an existing middleware (scaffolds rules + leaves it, verify not wired)', () => {
    const dir = tmp('ps-next2-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', dependencies: { next: '^14.0.0' } }));
    const ownMiddleware = 'export function middleware() { /* my own */ }\n';
    writeFileSync(path.join(dir, 'middleware.ts'), ownMiddleware);
    try {
      runProtect(dir);
      expect(read(dir, 'middleware.ts')).toBe(ownMiddleware); // untouched
      expect(existsSync(path.join(dir, 'patchstack.rules.json'))).toBe(true); // rules still scaffolded
      expect(runVerify(dir).wired).toBe(false); // guard not in their middleware
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('SvelteKit adapter', () => {
  it('scaffolds src/hooks.server.ts + co-located rules when none exists', () => {
    const dir = tmp('ps-svelte-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', devDependencies: { '@sveltejs/kit': '^2.0.0' } }));
    try {
      const res: any = runProtect(dir);
      expect(res.status).toBe('wired');
      expect(res.adapter).toBe('sveltekit');
      const hooks = read(dir, 'src/hooks.server.ts');
      expect(hooks).toContain('patchstack-sveltekit');
      expect(hooks).toContain('export const handle');
      expect(existsSync(path.join(dir, 'src/patchstack.rules.json'))).toBe(true);
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('does NOT overwrite an existing hooks.server.ts (verify not wired)', () => {
    const dir = tmp('ps-svelte2-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', devDependencies: { '@sveltejs/kit': '^2.0.0' } }));
    mkdirSync(path.join(dir, 'src'), { recursive: true });
    const own = 'export const handle = async ({ event, resolve }) => resolve(event);\n';
    writeFileSync(path.join(dir, 'src/hooks.server.ts'), own);
    try {
      runProtect(dir);
      expect(read(dir, 'src/hooks.server.ts')).toBe(own); // untouched
      expect(existsSync(path.join(dir, 'src/patchstack.rules.json'))).toBe(true);
      expect(runVerify(dir).wired).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('Astro adapter', () => {
  it('scaffolds src/middleware.ts + co-located rules when none exists', () => {
    const dir = tmp('ps-astro-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', dependencies: { astro: '^4.0.0' } }));
    try {
      const res: any = runProtect(dir);
      expect(res.status).toBe('wired');
      expect(res.adapter).toBe('astro');
      const mw = read(dir, 'src/middleware.ts');
      expect(mw).toContain('patchstack-astro');
      expect(mw).toContain('export const onRequest');
      expect(existsSync(path.join(dir, 'src/patchstack.rules.json'))).toBe(true);
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('Fastify adapter', () => {
  function fastifyApp(): string {
    const dir = tmp('ps-fastify-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', dependencies: { fastify: '^4.26.0' } }));
    mkdirSync(path.join(dir, 'src'), { recursive: true });
    writeFileSync(path.join(dir, 'src/server.ts'), "import Fastify from 'fastify';\nconst app = fastify();\napp.listen({ port: 3000 });\n");
    return dir;
  }

  it('scaffolds the plugin and registers app.register(patchstackFastify) after the fastify() app', () => {
    const dir = fastifyApp();
    try {
      const res: any = runProtect(dir);
      expect(res.status).toBe('wired');
      expect(res.adapter).toBe('fastify');
      expect(read(dir, 'src/patchstack/guard.ts')).toContain('patchstackFastify');
      const server = read(dir, 'src/server.ts');
      expect(server).toContain('import { patchstackFastify } from "./patchstack/guard";');
      expect(server).toContain('app.register(patchstackFastify);');
      expect(server.indexOf('const app = fastify()')).toBeLessThan(server.indexOf('app.register(patchstackFastify)'));
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('is idempotent (re-run does not duplicate the registration)', () => {
    const dir = fastifyApp();
    try {
      runProtect(dir);
      runProtect(dir);
      expect(count(read(dir, 'src/server.ts'), 'app.register(patchstackFastify)')).toBe(1);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('NestJS adapter', () => {
  function nestApp(): string {
    const dir = tmp('ps-nest-');
    writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'x', dependencies: { '@nestjs/core': '^10.0.0' } }));
    mkdirSync(path.join(dir, 'src'), { recursive: true });
    writeFileSync(
      path.join(dir, 'src/main.ts'),
      "import { NestFactory } from '@nestjs/core';\nimport { AppModule } from './app.module';\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  await app.listen(3000);\n}\nbootstrap();\n",
    );
    return dir;
  }

  it('scaffolds the guard and wires app.use(patchstackMiddleware) after NestFactory.create', () => {
    const dir = nestApp();
    try {
      const res: any = runProtect(dir);
      expect(res.status).toBe('wired');
      expect(res.adapter).toBe('nestjs');
      expect(existsSync(path.join(dir, 'src/patchstack/guard.ts'))).toBe(true);
      const main = read(dir, 'src/main.ts');
      expect(main).toContain('import { patchstackMiddleware } from "./patchstack/guard";');
      expect(main).toContain('app.use(patchstackMiddleware);');
      expect(main.indexOf('NestFactory.create')).toBeLessThan(main.indexOf('app.use(patchstackMiddleware)'));
      expect(runVerify(dir).wired).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('is idempotent (re-run does not duplicate the middleware)', () => {
    const dir = nestApp();
    try {
      runProtect(dir);
      runProtect(dir);
      expect(count(read(dir, 'src/main.ts'), 'app.use(patchstackMiddleware)')).toBe(1);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
